events { worker_connections 1024; }

http {
  upstream api {
    server api-gateway:3005;
  }

  upstream spoilage {
    server spoilage-engine:8080;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://api/;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /spoilage/ {
      proxy_pass http://spoilage/;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
